import "@/styles/main.scss";
import "@fortawesome/fontawesome-free/css/all.css";
import "react-toastify/dist/ReactToastify.css";
import "react-datepicker/dist/react-datepicker.css";
import "rc-slider/assets/index.css";
import "rc-tooltip/assets/bootstrap.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import store from "@/app/store";
import Layout from "@/components/layout/layout";
import Loader from "@/components/common/loader/loader";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Layout>
        <Head>
          <title>BPK - PE - Apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="Denso-normal.js" type="module"></script>
          {/* <script src="test.js"></script> */}
        </Head>
        <Component {...pageProps} />
        <ToastContainer
          theme="dark"
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
        <Loader />
      </Layout>
    </Provider>
  );
}

export default MyApp;
