import '@/styles/globals.css'
import '@/styles/main.scss'
import '@fortawesome/fontawesome-free/css/all.css'
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux';
import store from '@/app/store';
import Layout from '@/components/layout/layout'
import { ToastContainer } from 'react-toastify'


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Layout>
        <Head>
          <title>BPK - PE - Apps</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />
      </Layout>
    </Provider>
  )
}

export default MyApp
