import '@/styles/globals.css'
import '@/styles/main.scss'
import 'react-toastify/dist/ReactToastify.css';
import Head from 'next/head';
import type { AppProps } from 'next/app'
import Layout from '@/components/layout'
import { ToastContainer } from 'react-toastify'


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Head>
        <title>BPK - PE - Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/icons/css/all.css" rel="stylesheet"/>
      </Head>
      <Component {...pageProps} />
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
    </Layout>
  )
}

export default MyApp
